# Generated by Django 5.2.8 on 2025-12-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['region__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='stations.cercle')),
            ],
            options={
                'ordering': ['cercle__region__nom', 'cercle__nom', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='cercle',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cercles', to='stations.region'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.commune')),
                ('gerant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['commune__cercle__region__nom', 'commune__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=50)),
                ('ancien_niveau', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_niveau', models.CharField(max_length=20)),
                ('date_maj', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_stocks', to='stations.station')),
            ],
            options={
                'ordering': ['-date_maj'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('Super', 'Super'), ('Gasoil', 'Gasoil'), ('Pétrole', 'Pétrole')], max_length=50)),
                ('niveau', models.CharField(choices=[('Bas', 'Bas'), ('Moyen', 'Moyen'), ('Plein', 'Plein'), ('Rupture', 'Rupture')], max_length=20)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stations.station')),
            ],
            options={
                'ordering': ['-date_maj'],
                'unique_together': {('station', 'produit')},
            },
        ),
    ]
