# Generated by Django 5.2.8 on 2025-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.CharField(choices=[('Super', 'Essence'), ('Gasoil', 'Gasoil')], max_length=50),
        ),
    ]
