# Generated by Django 5.2.8 on 2025-12-12 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stock_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='station',
        ),
        migrations.AlterModelOptions(
            name='cercle',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('nom',)},
        ),
        migrations.RemoveField(
            model_name='station',
            name='gerant',
        ),
        migrations.AddField(
            model_name='station',
            name='cercle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.cercle'),
        ),
        migrations.AddField(
            model_name='station',
            name='essence_niveau',
            field=models.CharField(choices=[('plein', 'Plein'), ('moyen', 'Moyen'), ('bas', 'Bas'), ('rupture', 'Rupture'), ('inconnu', 'Inconnu')], default='inconnu', max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='gasoil_niveau',
            field=models.CharField(choices=[('plein', 'Plein'), ('moyen', 'Moyen'), ('bas', 'Bas'), ('rupture', 'Rupture'), ('inconnu', 'Inconnu')], default='inconnu', max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stations.region'),
        ),
        migrations.AddField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.commune'),
        ),
        migrations.AlterField(
            model_name='station',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='cercle',
            unique_together={('region', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('cercle', 'nom')},
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
