# Generated by Django 6.0 on 2025-12-14 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_remove_stockhistory_station_alter_cercle_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cercle',
            options={'ordering': ['region__nom', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'ordering': ['cercle__region__nom', 'cercle__nom', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['commune__cercle__region__nom', 'commune__nom', 'nom']},
        ),
        migrations.AlterUniqueTogether(
            name='cercle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='station',
            name='cercle',
        ),
        migrations.RemoveField(
            model_name='station',
            name='essence_niveau',
        ),
        migrations.RemoveField(
            model_name='station',
            name='gasoil_niveau',
        ),
        migrations.RemoveField(
            model_name='station',
            name='region',
        ),
        migrations.RemoveField(
            model_name='station',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='station',
            name='gerant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.commune'),
        ),
        migrations.AlterField(
            model_name='station',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=50)),
                ('ancien_niveau', models.CharField(blank=True, max_length=20, null=True)),
                ('nouveau_niveau', models.CharField(max_length=20)),
                ('date_maj', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_stocks', to='stations.station')),
            ],
            options={
                'ordering': ['-date_maj'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('Super', 'Essence'), ('Gasoil', 'Gasoil')], max_length=50)),
                ('niveau', models.CharField(choices=[('Bas', 'Bas'), ('Moyen', 'Moyen'), ('Plein', 'Plein'), ('Rupture', 'Rupture')], max_length=20)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stations.station')),
            ],
            options={
                'ordering': ['-date_maj'],
                'unique_together': {('station', 'produit')},
            },
        ),
    ]
