# Generated by Django 6.0 on 2025-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_cercle_options_alter_commune_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.CharField(choices=[('essence', 'Essence'), ('gasoil', 'Gasoil')], max_length=50),
        ),
    ]
