# Generated by Django 6.0 on 2025-12-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_stock_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='niveau',
            field=models.CharField(choices=[('Bas', 'Bas'), ('Moyen', 'Faible'), ('Plein', 'Plein'), ('Rupture', 'Rupture')], max_length=20),
        ),
    ]
