# Generated by Django 6.0 on 2026-01-17 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_device_stationsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(blank=True, choices=[('essence', 'Essence'), ('gasoil', 'Gasoil')], max_length=50, null=True)),
                ('notify_on_levels', models.CharField(choices=[('Plein', 'Seulement Plein'), ('Plein,Faible,Bas', 'Plein/Faible/Bas')], default='Plein,Faible,Bas', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='stationsubscription',
            name='uniq_user_station_sub',
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station'),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stationfollow',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='stations.station'),
        ),
        migrations.AddField(
            model_name='stationfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.RemoveField(
            model_name='stationsubscription',
            name='station',
        ),
        migrations.RemoveField(
            model_name='stationsubscription',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='stationfollow',
            constraint=models.UniqueConstraint(fields=('user', 'station', 'produit'), name='uniq_follow_user_station_product'),
        ),
        migrations.DeleteModel(
            name='StationSubscription',
        ),
    ]
