# Generated by Django 6.0 on 2026-01-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_inappnotification_stationfollow_remove_device_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationfollow',
            name='notify_on_levels',
            field=models.CharField(choices=[('Plein', 'Seulement Plein')], default='Plein', max_length=50),
        ),
    ]
