# Generated by Django 6.0 on 2026-01-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fcm_token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('platform', models.CharField(default='android', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(blank=True, choices=[('essence', 'Essence'), ('gasoil', 'Gasoil')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_follows', to='stations.device')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_followers', to='stations.station')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'station', 'produit'), name='uniq_follow_device_station_product')],
            },
        ),
    ]
