# Generated by Django 6.0 on 2026-01-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_device_devicefollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceToken',
        ),
    ]
