# Generated by Django 6.0 on 2026-06-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_delete_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='stations.commune'),
        ),
    ]
