# Generated by Django 6.0 on 2026-06-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_alter_station_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
