# Generated by Django 6.0 on 2026-01-26 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(db_index=True)),
                ('produit', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('kind', models.CharField(db_index=True, max_length=50)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['station_id', 'produit', 'kind', 'key', 'created_at'], name='notificatio_station_41ca4f_idx')],
            },
        ),
    ]
