# Generated by Django 6.0 on 2026-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(db_index=True, default='legacy-device', max_length=120),
            preserve_default=False,
        ),
    ]
